const URL="https://tbjlwhbwcxdvagjoonwb.supabase.co",KEY="sb_publishable_z2AUPoYHLMqxxizwKrjhwQ_tESJhSxp",DATA="https://raw.githubusercontent.com/letzbug/franks_magic/ee1deb187cb56360699bb18606d7685de65d9e6c/data/trainings.json";
const sb=window.supabase.createClient(URL,KEY),$=s=>document.querySelector(s);let users=[],names=[];
const norm=s=>String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]/g,"");
async function fn(action,payload={}){const {data:{session}}=await sb.auth.getSession();const r=await fetch(`${URL}/functions/v1/access-manager`,{method:"POST",headers:{"Content-Type":"application/json","apikey":KEY,"Authorization":`Bearer ${session?.access_token||""}`},body:JSON.stringify({action,...payload})});const b=await r.json();if(!r.ok||b.error)throw Error(b.error||`Erreur ${r.status}`);return b}
async function trainerNames(){try{const d=await (await fetch(DATA,{cache:"no-store"})).json(),m=new Map();d.forEach(c=>(c.enseignants||[]).forEach(e=>{const n=`${e.prenom||""} ${e.nom||""}`.trim();if(n)m.set(norm(n),n)}));names=[...m.values()].sort((a,b)=>a.localeCompare(b,"fr"));$("#names").innerHTML=names.map(n=>`<option value="${n.replaceAll('"',"&quot;")}">`).join("")}catch(e){console.warn(e)}}
async function isAdmin(){const {data:{session}}=await sb.auth.getSession();if(!session)return false;const {data}=await sb.from("trainer_access").select("role,active,deleted_at").eq("auth_user_id",session.user.id).maybeSingle();return !!(data&&data.role==="admin"&&data.active&&!data.deleted_at)}
async function boot(){const ok=await isAdmin();$("#gate").classList.toggle("hidden",ok);$("#app").classList.toggle("hidden",!ok);$("#logout").classList.toggle("hidden",!ok);if(ok){await trainerNames();await load()}}
$("#login").onclick=async()=>{const {error}=await sb.auth.signInWithPassword({email:$("#email").value.trim(),password:$("#password").value});$("#gateStatus").textContent=error?error.message:"";await boot()}
$("#logout").onclick=async()=>{await sb.auth.signOut();boot()}
$("#create").onclick=async()=>{let role=$("#role").value,email=$("#trainerEmail").value.trim().toLowerCase(),name=$("#trainer").value.trim();if(!email)return $("#createStatus").textContent="E-mail obligatoire.";if(role==="trainer"){name=names.find(n=>norm(n)===norm(name));if(!name)return $("#createStatus").textContent="Choisissez un formateur du catalogue."}else name=null;try{const b=await fn("authorize",{email,trainer_name:name,role});$("#createStatus").innerHTML=`Accès prêt. Code: <span class="code">${b.code}</span> (à transmettre au formateur)`;$("#trainer").value="";$("#trainerEmail").value="";await load()}catch(e){$("#createStatus").textContent=e.message}}
function render(){const q=$("#search").value.trim().toLowerCase(),a=users.filter(u=>!q||String(u.trainer_name||"Administrateur").toLowerCase().includes(q)||u.email.toLowerCase().includes(q));$("#count").textContent=`${users.length} accès`;$("#list").innerHTML=a.map(u=>`<div class="row" data-id="${u.id}"><div class="who"><strong>${u.trainer_name||"Administrateur UniPop Go"}</strong><span>${u.email}</span><div class="badges"><span class="badge ${u.active?"ok":"blocked"}">${u.active?"Actif":"Bloqué"}</span><span class="badge">${u.role}</span>${u.activation_code?`<span class="badge">Code en attente</span>`:""}</div></div><div class="actions">${u.activation_code?`<button data-a="copy">Copier code</button>`:""}<button data-a="reset">Nouveau code</button><button data-a="toggle">${u.active?"Bloquer":"Réactiver"}</button><button class="danger" data-a="delete">Supprimer</button></div></div>`).join("");document.querySelectorAll(".row button").forEach(b=>b.onclick=()=>act(b.closest(".row").dataset.id,b.dataset.a))}
async function load(){const {data,error}=await sb.from("trainer_access").select("id,email,trainer_name,role,active,activation_code,deleted_at").is("deleted_at",null).order("trainer_name");if(error)return alert(error.message);users=data||[];render()}
async function act(id,a){const u=users.find(x=>x.id===id);try{if(a==="copy"){await navigator.clipboard.writeText(u.activation_code);alert(`Code copié: ${u.activation_code}`);return}if(a==="reset"){const b=await fn("reset_code",{id});alert(`Nouveau code: ${b.code}`)}if(a==="toggle")await fn("set_active",{id,active:!u.active});if(a==="delete"&&confirm(`Supprimer l'accès de ${u.trainer_name||u.email} ?`))await fn("archive",{id});await load()}catch(e){alert(e.message)}}
$("#search").oninput=render;boot();